name: test site again
favicon: null
layout_spectrum: 0.24815917410887778
typography_spectrum: 0.4006479464005679
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5131010585464537
  lightness: 0.15971625410020351
  saturation: 0.7799850217998028
  rhythmicContrast: 0.1468112727161497
purpose: []
